name = "metnum"
uuid = "44dac47c-a70e-11e8-3cff-fbf5f1b7c554"
license = "MIT"
authors = ["Mohamad Khoirun Najib <mkhoirun_najib@apps.ipb.ac.id>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
